language: rust

cache:
  - cargo

rust:
  - nightly

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose

after_success:
  - test $TRAVIS_BRANCH = "master" -a $TRAVIS_RUST_VERSION = "nightly" &&
    cargo doc &&
    echo '<html><head><meta http-equiv=refresh content=0;url=syn_flood/index.html /></head></html>' > target/doc/index.html

deploy:
  provider: pages
  local-dir: target/doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
    condition: $TRAVIS_RUST_VERSION = nightly