
name: CI
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [nightly]

    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@master
        with:
          command: fmt
          args: -- --check

      - uses: actions-rs/cargo@master
        with:
          command: build
          args: --all-targets

      - uses: actions-rs/cargo@master
        with:
          command: test
          args: --all-targets

      - uses: actions-rs/cargo@master
        with:
          command: clippy
          args: --all-targets -- -D warnings

      - uses: actions-rs/cargo@master
        with:
          command: doc

      - uses: peaceiris/actions-gh-pages@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc


  doc:
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ github.ref == 'master' }}

    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@master
        with:
          command: doc

      - uses: peaceiris/actions-gh-pages@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc

