
name: Documentation
on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@master
        with:
          command: doc

      - uses: peaceiris/actions-gh-pages@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc
